#!/usr/bin/env bash
# Integration test for stackpanel
# 
# This test:
# 1. Creates a temp directory
# 2. Copies the template
# 3. Adds stackpanel as a local flake input
# 4. Adds test team data
# 5. Runs generate and verifies output
#
# Usage: ./tests/integration.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log() { echo -e "${GREEN}[TEST]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# Create temp directory
TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT
log "Created temp directory: $TMPDIR"

# Copy template
cp -r "$REPO_ROOT/templates/default/"* "$TMPDIR/"
cp -r "$REPO_ROOT/templates/default/".* "$TMPDIR/" 2>/dev/null || true
log "Copied template to temp directory"

cd "$TMPDIR"

# Create flake.nix that uses local stackpanel
cat > flake.nix << 'EOF'
{
  description = "Integration test project";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-parts.url = "github:hercules-ci/flake-parts";
    stackpanel.url = "STACKPANEL_PATH";
  };

  outputs = inputs@{ flake-parts, ... }:
    flake-parts.lib.mkFlake { inherit inputs; } {
      imports = [
        inputs.stackpanel.flakeModules.default
      ];

      systems = [ "x86_64-linux" "aarch64-linux" "aarch64-darwin" "x86_64-darwin" ];

      perSystem = { config, pkgs, ... }: 
      let
        teamData = import ./.stackpanel/team.nix;
      in {
        stackpanel = {
          secrets = {
            enable = true;
            users = teamData.users;
            secrets = {
              "api-key.age".owners = [ "alice" "bob" ];
              "db-password.age".owners = [ "alice" ];
            };
            rekey.enable = true;
          };

          ci.github = {
            enable = true;
            checks = {
              enable = true;
              commands = [ "nix flake check" "nix build" ];
            };
          };
        };
      };
    };
}
EOF

# Replace placeholder with actual path
sed -i.bak "s|STACKPANEL_PATH|path:$REPO_ROOT|g" flake.nix
rm -f flake.nix.bak
log "Created flake.nix with local stackpanel input"

# Create test team data (simulating agent output)
cat > .stackpanel/team.nix << 'EOF'
# Generated by stackpanel agent (test data)
{
  users = {
    alice = {
      github = "alice";
      pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAITestKeyAlice";
      admin = true;
    };
    bob = {
      github = "bob";
      pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAITestKeyBob";
      admin = false;
    };
  };
}
EOF
log "Created test team data"

# Initialize git (required for flakes)
git init -q
git add -A
log "Initialized git repository"

# Run generate-diff first (dry run)
log "Running generate-diff..."
nix run .#generate-diff 2>&1 || error "generate-diff failed"

# Run generate
log "Running generate..."
nix run .#generate 2>&1 || error "generate failed"

# Verify outputs
log "Verifying generated files..."

# Check secrets/secrets.nix
if [[ ! -f "secrets/secrets.nix" ]]; then
  error "secrets/secrets.nix not generated"
fi
if ! grep -q "alice" secrets/secrets.nix; then
  error "secrets/secrets.nix missing alice"
fi
if ! grep -q "bob" secrets/secrets.nix; then
  error "secrets/secrets.nix missing bob"
fi
log "✓ secrets/secrets.nix looks correct"

# Check CI workflow
if [[ ! -f ".github/workflows/ci.yml" ]]; then
  error ".github/workflows/ci.yml not generated"
fi
if ! grep -q "nix flake check" .github/workflows/ci.yml; then
  error "ci.yml missing 'nix flake check' command"
fi
log "✓ .github/workflows/ci.yml looks correct"

# Check rekey workflow
if [[ ! -f ".github/workflows/rekey.yml" ]]; then
  error ".github/workflows/rekey.yml not generated"
fi
if ! grep -q "agenix" .github/workflows/rekey.yml; then
  error "rekey.yml missing agenix"
fi
log "✓ .github/workflows/rekey.yml looks correct"

# Check .stackpanel/.gitignore
if [[ ! -f ".stackpanel/.gitignore" ]]; then
  error ".stackpanel/.gitignore not generated"
fi
log "✓ .stackpanel/.gitignore exists"

echo ""
log "========================================="
log "All integration tests passed! ✓"
log "========================================="
