# Secrets management - user/team pubkeys + agenix wiring
#
# Flow when user clicks "Install Agenix" in UI:
#   1. Agent fetches GitHub team members + their SSH pubkeys
#   2. Agent writes to .stackpanel/secrets.nix (or inline in flake)
#   3. User runs `nix run .#generate`
#   4. Files written: secrets/secrets.nix, .github/workflows/rekey.yml
#
{ lib, flake-parts-lib, ... }:
let
  inherit (flake-parts-lib) mkPerSystemOption;
in {
  options.perSystem = mkPerSystemOption ({ config, pkgs, ... }:
  let
    cfg = config.stackpanel.secrets;

    # YAML generation
    yaml = pkgs.formats.yaml {};
    toYaml = attrs: builtins.readFile (yaml.generate "workflow.yml" attrs);

  # All admins get access to all secrets automatically
  admins = lib.filterAttrs (_: u: u.admin) cfg.users;
  adminNames = lib.attrNames admins;

  # Generate agenix-compatible secrets.nix content
  secretsNixContent = let
    userDefs = lib.concatStringsSep "\n" (lib.mapAttrsToList (name: u:
      "  ${name} = \"${u.pubkey}\";"
    ) cfg.users);

    # For each secret, include explicit owners + all admins
    secretDefs = lib.concatStringsSep "\n" (lib.mapAttrsToList (name: s:
      let
        allOwners = lib.unique (s.owners ++ adminNames);
        ownerRefs = lib.concatStringsSep " " allOwners;
      in "  \"${name}\".publicKeys = [ ${ownerRefs} ];"
    ) cfg.secrets);
  in ''
    # Generated by stackpanel - do not edit manually
    # To modify, update stackpanel.secrets in your flake.nix
    let
    ${userDefs}
    in
    {
    ${secretDefs}
    }
  '';

  # GitHub Actions workflow for automatic rekeying
  rekeyWorkflow = {
    name = "Rekey Secrets";
    on = {
      push = {
        branches = cfg.rekey.branches;
        paths = [ "secrets/secrets.nix" ];
      };
      workflow_dispatch = {};
    };
    permissions.contents = "write";
    jobs.rekey = {
      runs-on = cfg.rekey.runsOn;
      steps = [
        { name = "Checkout"; uses = "actions/checkout@v4"; }
        { name = "Install Nix"; uses = "cachix/install-nix-action@v30"; }
        {
          name = "Setup SSH key";
          run = ''
            mkdir -p ~/.ssh
            echo "${"$"}{{ secrets.${cfg.rekey.sshKeySecret} }}" > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/id_ed25519
          '';
        }
        { name = "Install agenix"; run = "nix profile install github:ryantm/agenix"; }
        { name = "Rekey"; run = "cd secrets && agenix -r"; }
        {
          name = "Commit changes";
          run = ''
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git diff --quiet secrets/*.age || (git add secrets/*.age && git commit -m "chore: rekey secrets" && git push)
          '';
        }
      ];
    };
  };

  in {
    options.stackpanel.secrets = {
    enable = lib.mkEnableOption "secrets management";

    users = lib.mkOption {
      type = lib.types.attrsOf (lib.types.submodule {
        options = {
          pubkey = lib.mkOption {
            type = lib.types.str;
            description = "SSH public key (ssh-ed25519 ...)";
          };
          github = lib.mkOption {
            type = lib.types.str;
            default = "";
            description = "GitHub username (for display/lookup)";
          };
          admin = lib.mkOption {
            type = lib.types.bool;
            default = false;
            description = "Admin users can decrypt all secrets";
          };
        };
      });
      default = {};
      example = lib.literalExpression ''
        {
          alice = { pubkey = "ssh-ed25519 AAAA..."; github = "alice"; admin = true; };
          bob = { pubkey = "ssh-ed25519 AAAA..."; github = "bobdev"; };
        }
      '';
    };

    secrets = lib.mkOption {
      type = lib.types.attrsOf (lib.types.submodule {
        options = {
          owners = lib.mkOption {
            type = lib.types.listOf lib.types.str;
            default = [];
            description = "List of user names who can decrypt";
          };
        };
      });
      default = {};
      example = lib.literalExpression ''
        {
          "api-key.age".owners = [ "alice" "bob" ];
          "db-password.age".owners = [ "alice" ];  # admin only
        }
      '';
    };

    outputPath = lib.mkOption {
      type = lib.types.str;
      default = "secrets/secrets.nix";
      description = "Where to generate secrets.nix";
    };

    # Auto-rekey GitHub Action
    rekey = {
      enable = lib.mkEnableOption "GitHub Action to auto-rekey on push" // { default = true; };

      branches = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [ "main" ];
      };

      runsOn = lib.mkOption {
        type = lib.types.str;
        default = "ubuntu-latest";
      };

      sshKeySecret = lib.mkOption {
        type = lib.types.str;
        default = "AGENIX_SSH_KEY";
        description = "GitHub secret name containing CI SSH private key";
      };
    };
  };

    config = lib.mkIf cfg.enable {
      # secrets/secrets.nix - agenix configuration
      stackpanel.files.${cfg.outputPath} = secretsNixContent;

      # .github/workflows/rekey.yml - auto-rekey action
      stackpanel.files.".github/workflows/rekey.yml" =
        lib.mkIf cfg.rekey.enable (toYaml rekeyWorkflow);
    };
  });
}
