# Generated by stackpanel agent
# This file is safe to commit - it contains public keys only
{
  users = {
    # Add team members here or sync from GitHub via stackpanel agent
    # example = {
    #   github = "example";
    #   pubkey = "ssh-ed25519 AAAA...";
    #   admin = false;
    # };
  };
}
