# ============================================================================
# WHAT THE AGENT GENERATES
# ============================================================================
# When user clicks "Install Agenix" in localhost:1111, the agent:
#   1. Calls GitHub API to get team members
#   2. Fetches each member's SSH pubkeys from github.com/<user>.keys
#   3. Writes THIS FILE to .stackpanel/secrets.nix
#   4. The flake.nix imports this file
#
# This is the "database" - just a nix file that gets version controlled.
# ============================================================================

# .stackpanel/secrets.nix - GENERATED BY AGENT
{
  # Team synced from GitHub org "acme-corp" at 2024-12-10T15:30:00Z
  users = {
    alice = {
      github = "alice";
      pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExample1...";
      admin = true;  # org owner
    };
    bob = {
      github = "bobsmith";
      pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExample2...";
      admin = false;
    };
    charlie = {
      github = "charlie-dev";
      pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExample3...";
      admin = false;
    };
  };

  # CI system key - added by agent when enabling rekey workflow
  systems = {
    github-actions = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGitHubCI...";
  };
}
