// Generated by stackpanel - edits will be overwritten
// Regenerate with: nix run .#generate

/**
 * Server-side environment variables (all secrets)
 * Use with: import { serverEnv } from "./env";
 */
class ServerEnv {
  /**
   * PostgreSQL connection string
   * @required
   */
  get DATABASE_URL(): string {
    const value = process.env.DATABASE_URL;
    if (!value) throw new Error("Missing required env var: DATABASE_URL");
    return value;
  }
  /**
   * OpenAI API key for AI features
   * @optional
   */
  get OPENAI_API_KEY(): string | undefined {
    return process.env.OPENAI_API_KEY;
  }
  /**
   * Stripe API secret key
   * @required
   */
  get STRIPE_SECRET_KEY(): string {
    const value = process.env.STRIPE_SECRET_KEY;
    if (!value) throw new Error("Missing required env var: STRIPE_SECRET_KEY");
    return value;
  }
  /**
   * Google Analytics ID
   * @optional
   */
  get ANALYTICS_ID(): string | undefined {
    return process.env.ANALYTICS_ID;
  }
  /**
   * Stripe publishable key (safe for client)
   * @required
   */
  get STRIPE_PUBLISHABLE_KEY(): string {
    const value = process.env.STRIPE_PUBLISHABLE_KEY;
    if (!value) throw new Error("Missing required env var: STRIPE_PUBLISHABLE_KEY");
    return value;
  }
}

/**
 * Client-side environment variables (public only)
 * Safe to use in browser code
 * Use with: import { clientEnv } from "./env";
 */
class ClientEnv {
  /**
   * Google Analytics ID
   * @optional
   */
  get ANALYTICS_ID(): string | undefined {
    return process.env.PUBLIC_ANALYTICS_ID ?? process.env.NEXT_PUBLIC_ANALYTICS_ID;
  }
  /**
   * Stripe publishable key (safe for client)
   * @required
   */
  get STRIPE_PUBLISHABLE_KEY(): string {
    const value = process.env.PUBLIC_STRIPE_PUBLISHABLE_KEY ?? process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY;
    if (!value) throw new Error("Missing required env var: PUBLIC_STRIPE_PUBLISHABLE_KEY");
    return value;
  }
}

/** Server environment - all secrets */
export const serverEnv = new ServerEnv();

/** Client environment - public secrets only */
export const clientEnv = new ClientEnv();

/** Default export for convenience */
export default serverEnv;

// Type exports
export type ServerEnvKeys = "DATABASE_URL" | "OPENAI_API_KEY" | "STRIPE_SECRET_KEY" | "ANALYTICS_ID" | "STRIPE_PUBLISHABLE_KEY";
export type ClientEnvKeys = "ANALYTICS_ID" | "STRIPE_PUBLISHABLE_KEY";

