# .stackpanel directory support
# This is where the agent writes configuration data
#
# Pattern:
#   - Agent writes: .stackpanel/secrets.nix, .stackpanel/team.nix, etc.
#   - User's flake.nix imports from .stackpanel/
#   - Modules read this data and push to stackpanel.files
#   - `nix run .#generate` writes final output
#
{ lib, flake-parts-lib, ... }:
let
  inherit (flake-parts-lib) mkPerSystemOption;
in {
  options.perSystem = mkPerSystemOption ({ config, pkgs, ... }:
  let
    cfg = config.stackpanel;
  in {
    options.stackpanel = {
      # Directory where agent writes config data
      dataDir = lib.mkOption {
        type = lib.types.str;
        default = ".stackpanel";
        description = "Directory where stackpanel agent stores configuration data";
      };

      # Helper to import a file from dataDir if it exists
      # Usage: stackpanel.importData "secrets.nix" { users = {}; }
      importData = lib.mkOption {
        type = lib.types.functionTo lib.types.anything;
        default = filename: default:
          let path = "${cfg.dataDir}/${filename}";
          in if builtins.pathExists (builtins.toPath path)
             then import (builtins.toPath path)
             else default;
        description = "Import a file from dataDir with a default fallback";
        readOnly = true;
      };
    };

    config = lib.mkIf cfg.enable {
      # Generate a .gitignore for .stackpanel if it doesn't exist
      # Agent-generated files should be committed, but cache/state shouldn't
      stackpanel.files."${cfg.dataDir}/.gitignore" = ''
        # stackpanel data directory
        # These files are generated by the stackpanel agent and should be committed
        # Only ignore local cache/state
        
        cache/
        *.log
        .state
      '';
    };
  });
}
