# .stackpanel directory support
# Standalone module - no flake-parts dependency
#
# This is where the agent writes configuration data
#
# Pattern:
#   - Agent writes: .stackpanel/secrets.nix, .stackpanel/team.nix, etc.
#   - User's flake.nix imports from .stackpanel/
#   - Modules read this data and push to stackpanel.files
#   - `nix run .#generate` writes final output
#
{ lib, config, pkgs, ... }:
let
  cfg = config.stackpanel;
in {
  config = lib.mkIf cfg.enable {
    # Generate a .gitignore for .stackpanel if it doesn't exist
    # Agent-generated files should be committed, but cache/state shouldn't
    stackpanel.files."${cfg.dataDir}/.gitignore" = ''
      # stackpanel data directory
      # These files are generated by the stackpanel agent and should be committed
      # Only ignore local cache/state

      cache/
      *.log
      .state
    '';
  };
}
