# File generation system
# Exposes: `nix run .#generate` and `nix run .#generate-diff`
{ lib, flake-parts-lib, ... }:
let
  inherit (flake-parts-lib) mkPerSystemOption;
in {
  options.perSystem = mkPerSystemOption ({ pkgs, config, ... }:
  let
    cfg = config.stackpanel;
    files = cfg.files;
    header = cfg.generatedHeader;
    root = cfg.projectRoot;

    # Add header to text content
    withHeader = ext: content:
      let
        commentStyle = {
          nix = "#"; yml = "#"; yaml = "#"; sh = "#"; toml = "#";
          json = null;  # JSON doesn't support comments
          md = "<!--";
        };
        style = commentStyle.${ext} or "#";
      in
        if style == null then content
        else if style == "<!--" then "<!-- ${header} -->\n${content}"
        else "${style} ${header}\n${content}";

    getExt = path:
      let parts = lib.splitString "." path;
      in lib.last parts;

    # Only generate if there are files
    hasFiles = files != {};

  in {
    # stackpanel perSystem options
    options.stackpanel = {
      enable = lib.mkEnableOption "stackpanel" // { default = true; };

      projectRoot = lib.mkOption {
        type = lib.types.str;
        default = ".";
        description = "Root path for generated files";
      };

      generatedHeader = lib.mkOption {
        type = lib.types.str;
        default = "Generated by stackpanel - edits will be overwritten";
        description = "Header comment for generated files";
      };

      files = lib.mkOption {
        type = lib.types.attrsOf (lib.types.either lib.types.str lib.types.path);
        default = {};
        description = "Files to generate. path -> content";
      };
    };

    config = lib.mkIf cfg.enable {
      packages = {
        # nix run .#generate
        generate = pkgs.writeShellScriptBin "stackpanel-generate" (
          if hasFiles then ''
            set -euo pipefail
            cd "${root}"
            echo "Generating stackpanel files..."
            ${lib.concatStringsSep "\n" (lib.mapAttrsToList (path: content:
              let
                ext = getExt path;
                finalContent = if builtins.isPath content
                  then builtins.readFile content
                  else withHeader ext content;
              in ''
                mkdir -p "$(dirname "${path}")"
                cat > "${path}" << 'STACKPANEL_EOF'
${finalContent}
STACKPANEL_EOF
                echo "  ✓ ${path}"
              ''
            ) files)}
            echo "Done! Generated ${toString (lib.length (lib.attrNames files))} files."
          '' else ''
            echo "No files configured in stackpanel.files"
            echo "Add files in your flake.nix perSystem config"
          ''
        );

        # nix run .#generate-diff (dry run / preview)
        generate-diff = pkgs.writeShellScriptBin "stackpanel-generate-diff" (
          if hasFiles then ''
            echo "=== stackpanel managed files (${toString (lib.length (lib.attrNames files))}) ==="
            ${lib.concatStringsSep "\n" (lib.mapAttrsToList (path: content:
              let
                ext = getExt path;
                finalContent = if builtins.isPath content
                  then builtins.readFile content
                  else withHeader ext content;
              in ''
                echo ""
                echo "─── ${path} ───"
                cat << 'STACKPANEL_EOF'
${finalContent}
STACKPANEL_EOF
              ''
            ) files)}
          '' else ''
            echo "No files configured in stackpanel.files"
          ''
        );
      };
    };
  });
}
