# Core stackpanel options
# Standalone module - no flake-parts dependency
{ lib, config, pkgs, ... }:
let
  cfg = config.stackpanel;
in {
  options.stackpanel = {
    enable = lib.mkEnableOption "stackpanel" // { default = true; };

    projectRoot = lib.mkOption {
      type = lib.types.str;
      default = ".";
      description = "Root path for generated files";
    };

    generatedHeader = lib.mkOption {
      type = lib.types.str;
      default = "Generated by stackpanel - edits will be overwritten";
      description = "Header comment for generated files";
    };

    files = lib.mkOption {
      type = lib.types.attrsOf (lib.types.either lib.types.str lib.types.path);
      default = {};
      description = "Files to generate. path -> content";
    };

    # Directory where agent writes config data
    dataDir = lib.mkOption {
      type = lib.types.str;
      default = ".stackpanel";
      description = "Directory where stackpanel agent stores configuration data";
    };

    stateDir = lib.mkOption {
      type = lib.types.str;
      default = "${cfg.dataDir}/state";
      description = "Directory for stackpanel agent state/cache data";
    };

    # Helper to import a file from dataDir if it exists
    # Usage: stackpanel.importData "secrets.nix" { users = {}; }
    importData = lib.mkOption {
      type = lib.types.functionTo lib.types.anything;
      default = filename: default:
        let path = "${cfg.dataDir}/${filename}";
        in if builtins.pathExists (builtins.toPath path)
           then import (builtins.toPath path)
           else default;
      description = "Import a file from dataDir with a default fallback";
      readOnly = true;
    };

    # Packages generated by stackpanel modules
    packages = lib.mkOption {
      type = lib.types.attrsOf lib.types.package;
      default = {};
      description = "Packages generated by stackpanel modules";
    };
  };
}
