# Generated by stackpanel agent - safe to commit
# Last synced: 2024-12-10T15:30:00Z
# Source: github.com/orgs/acme-corp
{
  users = {
    alice = {
      github = "alice";
      pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExample1AliceKey";
      admin = true;
    };
    bob = {
      github = "bobsmith";
      pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExample2BobKey";
      admin = false;
    };
    charlie = {
      github = "charlie-dev";
      pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExample3CharlieKey";
      admin = false;
    };
  };
}
