# Generated by stackpanel agent - safe to commit
# Last synced: 2024-12-10T15:30:00Z
# Source: github.com/orgs/example-org
{
  users = {
    alice = {
      github = "alice";
      pubkey = "age1ql3z7hjy54pw3hyww5ayyfg7zqgvc7w3j2elw8zmrj2kg5sfn9aqmcac8p";
      admin = true;
    };
    bob = {
      github = "bobsmith";
      pubkey = "age1lzd99v4lnuqzs44lfjv9xp4e9k5jnmq4gfqzjq9z7f0fxz5emzrsy3v2zj";
      admin = false;
    };
    charlie = {
      github = "charlie-dev";
      pubkey = "age1m8ll9g9vfrqnf5m2pqkxhpvf3n6p4z7qg6f8yj8zhv3q9k2yjxcs5e6q8z";
      admin = false;
    };
  };
}