# Generated by stackpanel - edits will be overwritten
# Generated by stackpanel - do not edit manually
# To modify, update stackpanel.secrets in your flake.nix
let
  alice = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExample1AliceKey";
  bob = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExample2BobKey";
  charlie = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExample3CharlieKey";
in
{
  "api-key.age".publicKeys = [ alice bob ];
  "db-password.age".publicKeys = [ alice ];
  "stripe-key.age".publicKeys = [ alice bob charlie ];
}

